language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+browser-switch-android@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository
script: ./gradlew --info clean lint test
